name:                aoc-hs
version:             0.1.0.0
github:              "LATBauerdick/aoc-hs"
license:             BSD3
author:              "LATBauerdick"
maintainer:          "github@bauerdick.org"
copyright:           "2021 LATBauerdick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LATBauerdick/aoc-hs#readme>

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- relude
- hspec
- QuickCheck
- text
- containers
- split
- Unique

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-unused-binds

executables:
  aoc-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relude
    - aoc-hs

tests:
  aoc-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - aoc-hs
    - relude
